Week2/MVCWebApp/MVCWebApp/Models/DataForm.cs
namespace MVCWebApp.Models
{
    public class DataForm
    {
        public string Nama { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Passwordd { get; set; }
        public string Alamat { get; set; }
        public string JenisKelamin { get; set; }
        public string Pekerjaan { get; set; }
        public DateOnly TanggalMulai { get; set; }
        //[DisplayFormat(DataFormatString) = "0:MM/dd/yyyy")]
        public bool Penempatan { get; set; }
    }
}

Week2/MVCWebApp/MVCWebApp/Models/ErrorViewModel.cs
namespace MVCWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Week2/MVCWebApp/MVCWebApp/Models/Pegawai.cs
namespace MVCWebApp.Models
{
    // model / entity, domain object, business object
    public class Pegawai
    {
        public int Id { get; set; }
        public string Nama { get; set; }
        public string Email { get; set; }
    }
}

Week2/MVCWebApp/MVCWebApp/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCWebApp.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string bilangan1, string bilangan2, string operasi)
        {
            double bil1, bil2, hasil;
            bool isValidBil1 = double.TryParse(bilangan1, out bil1);
            bool isValidBil2 = double.TryParse(bilangan2, out bil2);

            ViewBag.Bil1 = string.Format("{0:#,##0}", bil1);
            ViewBag.Bil2 = string.Format("{0:#,##0}", bil2);
            ViewBag.Operasi = operasi;

            if (isValidBil1 && isValidBil2)
            {
                switch (ViewBag.Operasi)
                {
                    case "+":
                        hasil = bil1 + bil2;
                        ViewBag.Hasil = string.Format("{0:#,##0}", hasil);
                        break;
                    case "-":
                        hasil = bil1 - bil2;
                        ViewBag.Hasil = string.Format("{0:#,##0}", hasil);
                        break;
                    case "*":
                        hasil = bil1 * bil2;
                        ViewBag.Hasil = string.Format("{0:#,##0}", hasil); ;
                        break;
                    case "/":
                        if (bil2 != 0)
                        {
                            hasil = bil1 / bil2;
                            ViewBag.Hasil = string.Format("{0:#,##0}", hasil);
                        }
                        else
                        {
                            ViewBag.Error = "Error!";
                        }
                        break;
                    default:
                        ViewBag.Error = "Invalid operation!";
                        break;
                }
            }
            else
            {
                ViewBag.Error = "Invalid input!";
            }
            
            return View();
        }

    }
}

Week2/MVCWebApp/MVCWebApp/Controllers/FormPendaftaranController.cs
using Microsoft.AspNetCore.Mvc;
using MVCWebApp.Models;

namespace MVCWebApp.Controllers
{
    public class FormPendaftaranController : Controller
    {
        public IActionResult Registration()  
        {
            return View();
        }
        [HttpPost]
        public IActionResult Registration(DataForm d) 
        {
            ViewBag.Judul = "Data yang sudah diterima";

            return View("RegistrationDetails", d);
        }
    }
}

Week2/MVCWebApp/MVCWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCWebApp.Models;
using System.Diagnostics;

namespace MVCWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Week2/MVCWebApp/MVCWebApp/Controllers/TrainingController.cs
using Microsoft.AspNetCore.Mvc;
using MVCWebApp.Models;
using System.Drawing;

namespace MVCWebApp.Controllers
{
    public class TrainingController : Controller
    {
        public IActionResult Index() // /training/index
        {
            return View();
        }
        public IActionResult Hello() // /training/hello
        {
            return View();
            // return View("Test"); // jika tidak di otak-atik akan ikut nama diatasnya. bisa diganti dengan View(Test)
        }
        [HttpGet("training/test")] // rewrite router name ==> /test
        public IActionResult MyTest()
        {
            return View(); // nama view = nama fungsi
        }
        public IActionResult Pegawai() // training/pegawai
        {
            Pegawai p = new Pegawai { Id = 10, Nama = "Peg 10", Email = "peg10@gmail.com" };

            // viewbag
            ViewBag.Judul = "Hallo apa kabar";

            return View(p);
        }
        public IActionResult Detail(int id) // training/detail/(int id)
        {
            Pegawai p = new Pegawai { Id = id, Nama = "Peg 10", Email = "peg10@gmail.com" };

            // viewbag
            ViewBag.Judul = "Hallo apa kabar";

            return View("Pegawai", p);
        }
        public IActionResult Registration() // training/registration HTTP GET
        {
            return View();
        }
        [HttpPost]
        public IActionResult Registration(Pegawai peg) // training/registration HTTP POST
        {
            ViewBag.Judul = "Data yang sudah diterima";

            return View("Pegawai", peg);
        }
        public IActionResult MyRegistration() // training/myregistration HTTP GET
        {
            return View();
        }
        [HttpPost]
        public IActionResult MyRegistration(Pegawai mypeg) // training/myregistration HTTP POST
        {
            ViewBag.Judul = "Data yang sudah diterima";

            return View("Pegawai", mypeg);
        }
    }
}

Week2/MVCWebApp/MVCWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Week2/MVCWebApp/MVCWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Erzal Fahrezy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCWebApp.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><h3>Fahrezy</h3></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FormPendaftaran" asp-action="Registration">Registrasi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Index">Kalkulator</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ErzalWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>